---
# tasks file for mnn.varnish

- apt: name=apt-transport-https

- name: Add repo.varnish-cache.org pubkey
  apt_key: data="{{ lookup('file', 'repo.varnish-cache.org.pub') }}"
           state=present

- name: Add varnish-cache.org repo
  apt_repository: repo='deb https://repo.varnish-cache.org/ubuntu/ trusty varnish-{{ varnish_version|list|first }}.0'
                  state=present

- name: Install Varnish
  apt: name=varnish

- include: basicauth_vmod.yml
  when: varnish_basicauth

- name: Configure Varnish VCL
  template: src="{{ varnish_config_file }}" dest=/etc/varnish/
  notify: Reload Varnish

- name: Configure Varnish options
  template: src=default dest=/etc/default/varnish
  notify: Restart Varnish
